### ISSUE TITLE
"Weightings for the categories must equal 100%" error appearing when trying to save category percentages w/ extra credit

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1527]
Despite adding category weightings equaling 100%, attempts to save settings with cat & weighting in place result in a "Weightings for the categories must equal 100%" error message ONLY IF you happen to also have extra credit categories in place.

Removing the extra credit categories causes the settings to save successfully.

**Comment by steveswinsburg** [comment]
OK I have pushed a bunch of fixes for this. Extra credit items are excluded from the weight calculations, so I've updated the tally as well as the validation logic and also disabled the weight field if the extra credit box is checked. It is in PR #1551

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I think that, while EC items/categories are not included in the weight calculations, they do provide values that affect the weight calculations (confusing as that may be). So when an EC category is worth 10%, you will still have a GB weighting of 100%. BUT, if a student receives full points within that EC category, their course grade would end up as a 110%. In order for that extra 10% to be calculated as such, I would think that it needs to have a weight.

It looks like there is some form of weighting being capable of being associated with EC categories in GB1:
 
![image](https://cloud.githubusercontent.com/assets/11447474/12335629/2b1834ae-bace-11e5-8514-648197289b0f.png)

**Comment by steveswinsburg** [comment]
Ok as discussed on the call, remove the greying out of the weighting box if extra credit.

**Comment by kyleblythe** [comment]
Confirmed.
